### ISSUE TITLE
Stripe Payment hangs while Submitting - issue with reaction-core State Machine

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-stripe#5]
I haven't explored this project enough to fully understand what creates State Machine transitions, but when submitting payment through stripe, it gets hung after submitting the payment.

Specifically in `client/.../stripe/stripe.coffee` where it calls `CartWorkflow.paymentMethod(paymentMethod)`

When I check current state it is stuck in the 'cart' state for some reason, and checking the console, it fails with the "inappropriate in current state" State Machine exception.

I was able to resolved this on my local by adding `cart` to the list of from states for `paymentMethod`
_Edit: This is in the `workflow.coffee` file in reaction-core._
`    { name: "paymentMethod", from: ["cart","payment","paymentAuth","fetchShipmentMethods"], to: "paymentAuth"}`

I'm not submitting a PR because this feels like a hack, but I'd love to understand why it's getting stuck in the `cart` state.

**Comment by spencern** [comment]
I just tested this with a non-admin user, logged in via facebook during checkout flow, and didn't need the `workflow.coffee` hack, so my presumption is that the bug is related to already logged in users.

**Comment by aaronjudd** [comment]
@spencern thanks, I've not done much testing with development packages other than paypal. I'll keep an eye out for this as I update the packages to be development / 0.5.0 compatible prior to release (stripe might be fine, but haven't checked).

**Comment by aaronjudd** [comment]
I've just tested with release 0.5.0 and the latest development branch, and everything looks to be working ok now. I wasn't able to replicate - but there's a good chance this got taken care of somewhere else. If you can replicate I'll look into it further.
