### ISSUE TITLE
Bug: Card Number must be at least 16 characters

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-stripe#6]
Some valid cards are not 16 digits long. American Express for example uses the following format: 
3782 822463 10005 (Card number from Stripe valid Amex test number)

![image](https://cloud.githubusercontent.com/assets/1203639/6539288/ae144340-c42d-11e4-965f-a207f240d337.png)

Where are these validations defined?

**Comment by aaronjudd** [comment]
Yes, this is wrong. http://validcreditcardnumbers.info/?p=9  Validation is currently in the payment packages themselves.  ie: https://github.com/reactioncommerce/reaction-paypal/blob/development/common/collections.coffee#L34
